### ISSUE TITLE
Replace `reverse_diff` with `tracker` or remove this line

### ISSUE THREAD

**Issue by yiyuezhuo** [StatisticalRethinkingJulia/TuringModels.jl#30]
CompatHelper have suggested support for Turing 0.14 https://github.com/StatisticalRethinkingJulia/TuringModels.jl/pull/29 .

But as noted by this [comment](https://github.com/TuringLang/Turing.jl/blob/master/src/core/ad.jl#L20
), ad name `reverse_diff` is deprecated and will be removed, and exactly have been removed from `bijectors#master`, so now it will raise such error:

```
julia> Turing.setadbackend(:reverse_diff)
ERROR: MethodError: no method matching setadbackend(::Val{:reverse_diff})
Closest candidates are:
  setadbackend(::Val{:zygote}) at /home/yiyuezhuo/.julia/dev/Bijectors/src/interface.jl:21
  setadbackend(::Val{:tracker}) at /home/yiyuezhuo/.julia/dev/Bijectors/src/interface.jl:20
  setadbackend(::Val{:reversediff}) at /home/yiyuezhuo/.julia/dev/Bijectors/src/interface.jl:19
  ...
Stacktrace:
 [1] setadbackend(::Symbol) at /home/yiyuezhuo/.julia/packages/Turing/tf1R6/src/core/ad.jl:8
 [2] top-level scope at REPL[39]:1
```

So to properly support Turing 0.14 or incoming release, this line should be replaced with equivalence `:tracker`. I think the goal of commit of https://github.com/StatisticalRethinkingJulia/TuringModels.jl/commit/6b0d4b4b71082483222aa9730ec24eb6d665d9b9 which replaced `reversediff` with `reverse_diff` is that `ReverseDiff` is `using ReverseDiff` is missing, so this line just not works, while the goal of old commit https://github.com/StatisticalRethinkingJulia/TuringModels.jl/commit/dc67846ea5f14a3a441822bd51d924210461a564 which replaced `reverse_diff` with `reversediff` are considerations of efficiency and the fact that reverse_diff is outdated. As some experiments show `ReverseDiff` (`:reversediff` backend) is fastest backend in many cases.

But in my opinion, most models specified by TuringModels are small enough, so default `forwarddiff` is fastest in most cases. It may be better to just remove these lines (same reason `ForwardDiff` is selected as default AD instead of `Tracker`). Write tests to compare efficiency between `reversediff` and `forwarddiff` are also useful.

**Comment by goedman** [comment]
Thank you.

Rel 1.0.4 should work on J1.5 & J1.6.

I've removed the StatsPlots dependency, takes very long to compile (many error messages)

TuringModels is not really intended for performance, just to get going with the StatisticalRethinking models.
