### ISSUE TITLE
Unclarity about the corresponding book version

### ISSUE THREAD

**Issue by rikhuijzer** [StatisticalRethinkingJulia/TuringModels.jl#34]
It seems that model 13.2 does not correspond to the model in the statistical rethinking book version 2020. In the book, model 13.2 is about tadpoles and tanks, whereas the model in this repository is about gender and department.

Which version of the book is this repository corresponding to?

**Comment by goedman** [comment]
All ...Models.jl repositories are based on the first edition of the book. In the 2nd edition a chapter was added, the tank models were in chapter 12 in the 1st edn.

**Comment by rikhuijzer** [comment]
Ok, clear. Thank you
