### ISSUE TITLE
NUTS(0.65) versus NUTS(0.95)

### ISSUE THREAD

**Issue by rikhuijzer** [StatisticalRethinkingJulia/TuringModels.jl#42]
In dc67846ea5f14a3a441822bd51d924210461a564, Martin Trapp has replaced many occurrences of `NUTS(0.95)` with `NUTS(0.65)`. Still, I see both in this repository. Is there a reason why sometimes 0.65 should be used and at other times 0.95?

**Comment by goedman** [comment]
Not that I'm aware of. Originally when these models were developed Turing (Nuts) was a long way from where it is now! There are cases though where Turing has a harder time (compared to Stan) to work around a problem, e.g. in chapter 8 I believe there is a case. It would in fact be interesting to see if NUTS(0.65) would work in all models.

**Comment by rikhuijzer** [comment]
Check, I'll test it out when running the scripts.

**Comment by rikhuijzer** [comment]
This is now mostly fixed with #46. In general, 0.65 is better. Only if that fails, try 0.95.
