### ISSUE TITLE
Rename chains to chn

### ISSUE THREAD

**Issue by rikhuijzer** [StatisticalRethinkingJulia/TuringModels.jl#64]
In the scripts, the variable `chains` is used all over the place. Unfortunately, `chains` is also exported by `MCMCChains`, which can cause issues like
```
julia> chains = sample(model(a, b), NUTS(0.65), 1000)
ERROR: invalid redefinition of constant chains
```
Thanks to David Widmann for figuring this out (https://github.com/TuringLang/Turing.jl/issues/1529). 

To solve this issue, and avoid problems in the future for us and for users, we would be better of renaming the variables to `chn` or `chns` or something.

**Comment by BobinMathew** [comment]
Hi @rikhuijzer I would like to solve this issue 😀

**Comment by rikhuijzer** [comment]
Okay and thanks. I'll won't work on it then :+1: Looking forward to your pull request

**Comment by rikhuijzer** [comment]
Feel free to mail me or comment here if you have any questions
